/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.3.6-1-gbb0f553d75-g69dd1ce610+896"
#endif /* AVUTIL_FFVERSION_H */
